"$schema" = 'https://starship.rs/config-schema.json'

right_format = "$time"

[aws]
format = '[\[aws ($profile)(\($region\))(\[$duration\])\] ]($style)($style)'

[azure]
format = '[\[azure ($subscription)\] ]($style)($style)'

[battery]
format = '[\[battery $percentage\] ]($style)($style)'

[buf]
format = '[\[buf ($version)\] ]($style)($style)'

[bun]
format = '[\[bun ($version)\] ]($style)($style)'

[c]
format = '[\[c ($version(-$name))\] ]($style)($style)'

[cmake]
format = '[\[cmake ($version)\] ]($style)($style)'

[cmd_duration]
format = '[\[‚è± $duration\] ]($style)($style)'

[cobol]
format = '[\[cobol ($version)\] ]($style)($style)'

[conda]
format = '[\[conda $environment\] ]($style)($style)'

[container]
format = '[\[container \[$name\]\] ]($style)($style)'

[cpp]
format = '[\[cpp ($version(-$name))\] ]($style)($style)'

[crystal]
format = '[\[crystal ($version)\] ]($style)($style)'

[daml]
format = '[\[daml ($version)\] ]($style)($style)'

[dart]
format = '[\[dart ($version)\] ]($style)($style)'

[deno]
format = '[\[deno ($version)\] ]($style)($style)'

[direnv]
format = '[\[$symbol$loaded/$allowed\] ]($style)($style)'

[docker_context]
format = '[\[docker $context\] ]($style)($style)'

[dotnet]
format = '[\[dotnet ($version)(üéØ $tfm)\] ]($style)($style)'

[elixir]
format = '[\[elixir ($version \(OTP $otp_version\))\] ]($style)($style)'

[elm]
format = '[\[elm ($version)\] ]($style)($style)'

[erlang]
format = '[\[erlang ($version)\] ]($style)($style)'

[fennel]
format = '[\[fennel ($version)\] ]($style)($style)'

[fortran]
format = '[\[fortran ($version)\] ]($style)($style)'

[fossil_branch]
format = '[\[fossil $branch\] ]($style)($style)'

[fossil_metrics]
format = '[\[+$added]($added_style)\]\[[-$deleted]($deleted_style)\]'

[gcloud]
format = '[\[gcloud $account(@$domain)(\($region\))\] ]($style)($style)'

[git_branch]
format = '[\[git $branch\] ]($style)($style)'

[git_commit]
format = '[\[\($hash$tag\)\] ]($style)($style)'

[git_metrics]
format = '[\[+$added]($added_style)\]\[[-$deleted]($deleted_style)\]'

[git_state]
format = '[\[$state ($progress_current/$progress_total)\] ]($style)($style)'

[git_status]
format = '([\[$all_status$ahead_behind\] ]($style)($style))'

[gleam]
format = '[\[gleam ($version)\] ]($style)($style)'

[golang]
format = '[\[golang ($version)\] ]($style)($style)'

[gradle]
format = '[\[gradle ($version)\] ]($style)($style)'

[guix_shell]
format = '[\[guix\] ]($style)($style)'

[haskell]
format = '[\[haskell ($version)\] ]($style)($style)'

[haxe]
format = '[\[haxe ($version)\] ]($style)($style)'

[helm]
format = '[\[helm ($version)\] ]($style)($style)'

[hg_branch]
format = '[\[hg $branch\] ]($style)($style)'

[hostname]
format = '[\[ssh ($hostname)\] ]($style)($style) '

[java]
format = '[\[java ($version)\] ]($style)($style)'

[jobs]
format = '[\[jobs $number\] ]($style)($style)'

[julia]
format = '[\[julia ($version)\] ]($style)($style)'

[kotlin]
format = '[\[kotlin ($version)\] ]($style)($style)'

[kubernetes]
format = '[\[kubernetes $context( \($namespace\))\] ]($style)($style)'

[localip]
format = '[\[$localipv4\] ]($style)($style)'

[lua]
format = '[\[lua ($version)\] ]($style)($style)'

[memory_usage]
format = '\[memory [$ram( | $swap)\] ]($style)($style)'

[meson]
format = '[\[meson $project\] ]($style)($style)'

[mise]
format = '[\[mise $health\] ]($style)($style)'

[mojo]
format = '[\[mojo ($version)\] ]($style)($style)'

[nats]
format = '[\[nats $name\] ]($style)($style)'

[netns]
format = '[\[netns \[$name\]\] ]($style)($style)'

[nim]
format = '[\[nim ($version)\] ]($style)($style)'

[nix_shell]
format = '[\[nix $state( \($name\))\] ]($style)($style)'

[nodejs]
format = '[\[nodejs ($version)\] ]($style)($style)'

[ocaml]
format = '[\[ocaml ($version)(\($switch_indicator$switch_name\))\] ]($style)($style)'

[odin]
format = '[\[odin ($version )\] ]($style)($style)'

[opa]
format = '[\[opa ($version)\] ]($style)($style)'

[openstack]
format = '[\[openstack $cloud(\($project\))\] ]($style)($style)'

[os]
format = '[\[os\] ]($style)($style)'

[package]
format = '[\[pkg $version\] ]($style)($style)'

[perl]
format = '[\[perl ($version)\] ]($style)($style)'

[php]
format = '[\[php ($version)\] ]($style)($style)'

[pijul_channel]
format = '[\[pijul $channel\] ]($style)($style)'

[pixi]
format = '[\[pixi $version( $environment)\] ]($style)($style)'

[pulumi]
format = '[\[pulumi $stack\] ]($style)($style)'

[purescript]
format = '[\[purs ($version)\] ]($style)($style)'

[python]
format = '[\[py ${pyenv_prefix}(${version})(\($virtualenv\))\] ]($style)($style)'

[quarto]
format = '[\[quarto ($version)\] ]($style)($style)'

[raku]
format = '[\[raku ($version-$vm_version)\] ]($style)($style)'

[red]
format = '[\[red ($version)\] ]($style)($style)'

[rlang]
format = '[\[r ($version)\] ]($style)($style)'

[ruby]
format = '[\[rb ($version)\] ]($style)($style)'

[rust]
format = '[\[rs ($version)\] ]($style)($style)'

[scala]
format = '[\[scala ($version)\] ]($style)($style)'

[shell]
format = '[\[$indicator\] ]($style)($style)'

[singularity]
format = '[\[singularity \[$env\]\] ]($style)($style)'

[solidity]
format = '[\[solidity ($version)\] ]($style)($style)'

[spack]
format = '[\[spack $environment\] ]($style)($style)'

[status]
format = '[\[status $status\] ]($style)($style)'

[sudo]
format = '[\[as sudo\] ]($style)($style)'

[swift]
format = '[\[swift ($version)\] ]($style)($style)'

[terraform]
format = '[\[terraform $workspace\] ]($style)($style)'

[time]
format = '[\[$time\] ]($style)($style)'
disabled = false

[typst]
format = '[\[typst ($version)\] ]($style)($style)'

[username]
format = '[\[user: $user\] ]($style)($style)'

[vagrant]
format = '[\[vagrant ($version)\] ]($style)($style)'

[vcsh]
format = '\[vcsh [$repo\] ]($style)($style)'

[vlang]
format = '[\[vlang ($version)\] ]($style)($style)'

[xmake]
format = '[\[xmake ($version)\] ]($style)($style)'

[zig]
format = '[\[zig ($version)\] ]($style)($style)'