"$schema" = 'https://starship.rs/config-schema.json'

right_format = "$time"

[aws]
format = '[\[aws ($profile)(\($region\))(\[$duration\])\]]($style)'

[azure]
format = '[\[azure ($subscription)\]]($style)'

[battery]
format = '[\[battery $percentage\]]($style)'

[buf]
format = '[\[buf ($version)\]]($style)'

[bun]
format = '[\[bun ($version)\]]($style)'

[c]
format = '[\[c ($version(-$name))\]]($style)'

[cmake]
format = '[\[cmake ($version)\]]($style)'

[cmd_duration]
format = '[\[‚è± $duration\]]($style)'

[cobol]
format = '[\[cobol ($version)\]]($style)'

[conda]
format = '[\[conda $environment\]]($style)'

[container]
format = '[\[container \[$name\]\]]($style)'

[cpp]
format = '[\[cpp ($version(-$name))\]]($style)'

[crystal]
format = '[\[crystal ($version)\]]($style)'

[daml]
format = '[\[daml ($version)\]]($style)'

[dart]
format = '[\[dart ($version)\]]($style)'

[deno]
format = '[\[deno ($version)\]]($style)'

[direnv]
format = '[\[$symbol$loaded/$allowed\]]($style)'

[docker_context]
format = '[\[docker $context\]]($style)'

[dotnet]
format = '[\[dotnet ($version)(üéØ $tfm)\]]($style)'

[elixir]
format = '[\[elixir ($version \(OTP $otp_version\))\]]($style)'

[elm]
format = '[\[elm ($version)\]]($style)'

[erlang]
format = '[\[erlang ($version)\]]($style)'

[fennel]
format = '[\[fennel ($version)\]]($style)'

[fortran]
format = '[\[fortran ($version)\]]($style)'

[fossil_branch]
format = '[\[fossil $branch\]]($style)'

[fossil_metrics]
format = '[\[+$added]($added_style)\]\[[-$deleted]($deleted_style)\]'

[gcloud]
format = '[\[gcloud $account(@$domain)(\($region\))\]]($style)'

[git_branch]
format = '[\[git $branch\]]($style)'

[git_commit]
format = '[\[\($hash$tag\)\]]($style)'

[git_metrics]
format = '[\[+$added]($added_style)\]\[[-$deleted]($deleted_style)\]'

[git_state]
format = '[\[$state ($progress_current/$progress_total)\]]($style)'

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'

[gleam]
format = '[\[gleam ($version)\]]($style)'

[golang]
format = '[\[golang ($version)\]]($style)'

[gradle]
format = '[\[gradle ($version)\]]($style)'

[guix_shell]
format = '[\[guix\]]($style)'

[haskell]
format = '[\[haskell ($version)\]]($style)'

[haxe]
format = '[\[haxe ($version)\]]($style)'

[helm]
format = '[\[helm ($version)\]]($style)'

[hg_branch]
format = '[\[hg $branch\]]($style)'

[hostname]
format = '[\[ssh ($hostname)\]]($style) '

[java]
format = '[\[java ($version)\]]($style)'

[jobs]
format = '[\[jobs $number\]]($style)'

[julia]
format = '[\[julia ($version)\]]($style)'

[kotlin]
format = '[\[kotlin ($version)\]]($style)'

[kubernetes]
format = '[\[kubernetes $context( \($namespace\))\]]($style)'

[localip]
format = '[\[$localipv4\]]($style)'

[lua]
format = '[\[lua ($version)\]]($style)'

[memory_usage]
format = '\[memory [$ram( | $swap)\]]($style)'

[meson]
format = '[\[meson $project\]]($style)'

[mise]
format = '[\[mise $health\]]($style)'

[mojo]
format = '[\[mojo ($version)\]]($style)'

[nats]
format = '[\[nats $name\]]($style)'

[netns]
format = '[\[netns \[$name\]\]]($style)'

[nim]
format = '[\[nim ($version)\]]($style)'

[nix_shell]
format = '[\[nix $state( \($name\))\]]($style)'

[nodejs]
format = '[\[nodejs ($version)\]]($style)'

[ocaml]
format = '[\[ocaml ($version)(\($switch_indicator$switch_name\))\]]($style)'

[odin]
format = '[\[odin ($version )\]]($style)'

[opa]
format = '[\[opa ($version)\]]($style)'

[openstack]
format = '[\[openstack $cloud(\($project\))\]]($style)'

[os]
format = '[\[os\]]($style)'

[package]
format = '[\[pkg $version\]]($style)'

[perl]
format = '[\[perl ($version)\]]($style)'

[php]
format = '[\[php ($version)\]]($style)'

[pijul_channel]
format = '[\[pijul $channel\]]($style)'

[pixi]
format = '[\[pixi $version( $environment)\]]($style)'

[pulumi]
format = '[\[pulumi $stack\]]($style)'

[purescript]
format = '[\[purs ($version)\]]($style)'

[python]
format = '[\[py ${pyenv_prefix}(${version})(\($virtualenv\))\]]($style)'

[quarto]
format = '[\[quarto ($version)\]]($style)'

[raku]
format = '[\[raku ($version-$vm_version)\]]($style)'

[red]
format = '[\[red ($version)\]]($style)'

[rlang]
format = '[\[r ($version)\]]($style)'

[ruby]
format = '[\[rb ($version)\]]($style)'

[rust]
format = '[\[rs ($version)\]]($style)'

[scala]
format = '[\[scala ($version)\]]($style)'

[shell]
format = '[\[$indicator\]]($style)'

[singularity]
format = '[\[singularity \[$env\]\]]($style)'

[solidity]
format = '[\[solidity ($version)\]]($style)'

[spack]
format = '[\[spack $environment\]]($style)'

[status]
format = '[\[status $status\]]($style)'

[sudo]
format = '[\[as sudo\]]($style)'

[swift]
format = '[\[swift ($version)\]]($style)'

[terraform]
format = '[\[terraform $workspace\]]($style)'

[time]
format = '[\[$time\]]($style)'
disabled = false

[typst]
format = '[\[typst ($version)\]]($style)'

[username]
format = '[\[user: $user\]]($style)'

[vagrant]
format = '[\[vagrant ($version)\]]($style)'

[vcsh]
format = '\[vcsh [$repo\]]($style)'

[vlang]
format = '[\[vlang ($version)\]]($style)'

[xmake]
format = '[\[xmake ($version)\]]($style)'

[zig]
format = '[\[zig ($version)\]]($style)'