"$schema" = 'https://starship.rs/config-schema.json'

continuation_prompt = "[.](bright-black) "

right_format = "$time"

[time]
disabled = false
format = '\[[$time]($style)\]'

[character]
success_symbol = "[>](bold green)"
error_symbol = "[x](bold red)"
vimcmd_symbol = "[<](bold green)"
vimcmd_visual_symbol = "[<](bold yellow)"
vimcmd_replace_symbol = "[<](bold purple)"
vimcmd_replace_one_symbol = "[<](bold purple)"

[git_commit]
tag_symbol = " tag "

[git_status]
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "r"
deleted = "x"

[aws]
format = '\[[aws ($profile)(\($region\))(\[$duration\])]($style)\]'

[azure]
format = '\[[azure ($subscription)]($style)\]'

[battery]
format = '\[[battery ($percentage)]($style)\]'

[buf]
format = '\[[buf ($version)]($style)\]'

[bun]
format = '\[[bun ($version)]($style)\]'

[c]
format = '\[[c ($version(-$name))]($style)\]'

[cpp]
format = '\[[cpp ($version(-$name))]($style)\]'

[cobol]
format = '\[[cobol ($version)]($style)\]'

[conda]
format = '\[[conda$environment]($style)\]'

[container]
format = '\[[container \[$name\]]($style)\]'

[crystal]
format = '\[[crystal ($version)]($style)\]'

[cmake]
format = '\[[cmake ($version)]($style)\]'

[daml]
format = '\[[daml ($version)]($style)\]'

[dart]
format = '\[[dart ($version)]($style)\]'

[deno]
format = '\[[deno ($version)]($style)\]'

[dotnet]
format = '\[[dotnet ($version)(ðŸŽ¯ $tfm)]($style)\]'

[directory]
read_only = " ro"

[docker_context]
format = '\[[docker$context]($style)\]'

[elixir]
format = '\[[elixir ($version \(OTP $otp_version\))]($style)\]'

[elm]
format = '\[[elm ($version)]($style)\]'

[erlang]
format = '\[[erlang ($version)]($style)\]'

[fennel]
format = '\[[fennel ($version)]($style)\]'

[fortran]
format = '\[[fortran ($version)]($style)\]'

[fossil_branch]
symbol = "\\[fossil\\] "
truncation_symbol = "..."

[gcloud]
format = '\[[gcloud$account(@$domain)(\($region\))]($style)\]'

[git_branch]
format = '\[[git ($branch)]($style)\]'

[gleam]
format = '\[[gleam ($version)]($style)\]'

[golang]
format = '\[[golang ($version)]($style)\]'

[gradle]
format = '\[[gradle ($version)]($style)\]'

[guix_shell]
format = '\[[guix]\]'

[haskell]
format = '\[[haskell ($version)]($style)\]'

[haxe]
format = '\[[haxe ($version)]($style)\]'

[helm]
format = '\[[helm ($version)]($style)\]'

[hg_branch]
format = '\[[hg$branch]($style)\]'

[hostname]
format = '\[[ssh ($hostname)]($style)\] '

[java]
format = '\[[java ($version)]($style)\]'

[jobs]
format = '\[[jobs$number]($style)\]'

[julia]
format = '\[[julia ($version)]($style)\]'

[kotlin]
format = '\[[kotlin ($version)]($style)\]'

[kubernetes]
format = '\[[kubernetes$context( \($namespace\))]($style)\]'

[lua]
format = '\[[lua ($version)]($style)\]'

[nodejs]
format = '\[[nodejs ($version)]($style)\]'

[memory_usage]
format = '\[memory[$ram( | $swap)]($style)\]'

[meson]
format = '\[[meson$project]($style)\]'

[mojo]
format = '\[[mojo ($version)]($style)\]'

[nats]
format = '\[[nats$name]($style)\]'

[netns]
format = '\[[netns \[$name\]]($style)\]'

[nim]
format = '\[[nim ($version)]($style)\]'

[nix_shell]
format = '\[[nix$state( \($name\))]($style)\]'

[ocaml]
symbol = "\\[ml\\] "

[odin]
format = '\[[odin ($version )]($style)\]'

[opa]
format = '\[[opa ($version)]($style)\]'

[openstack]
format = '\[[openstack$cloud(\($project\))]($style)\]'

[os.symbols]
AIX = "aix "
Alpaquita = "alq "
AlmaLinux = "alma "
Alpine = "alp "
Amazon = "amz "
Android = "andr "
AOSC = "aosc "
Arch = "rch "
Artix = "atx "
Bluefin = "blfn "
CachyOS = "cach "
CentOS = "cent "
Debian = "deb "
DragonFly = "dfbsd "
Emscripten = "emsc "
EndeavourOS = "ndev "
Fedora = "fed "
FreeBSD = "fbsd "
Garuda = "garu "
Gentoo = "gent "
HardenedBSD = "hbsd "
Illumos = "lum "
Kali = "kali "
Linux = "lnx "
Mabox = "mbox "
Macos = "mac "
Manjaro = "mjo "
Mariner = "mrn "
MidnightBSD = "mid "
Mint = "mint "
NetBSD = "nbsd "
NixOS = "nix "
Nobara = "nbra "
OpenBSD = "obsd "
OpenCloudOS = "ocos "
openEuler = "oeul "
openSUSE = "osuse "
OracleLinux = "orac "
Pop = "pop "
Raspbian = "rasp "
Redhat = "rhl "
RedHatEnterprise = "rhel "
RockyLinux = "rky "
Redox = "redox "
Solus = "sol "
SUSE = "suse "
Ubuntu = "ubnt "
Ultramarine = "ultm "
Unknown = "unk "
Uos = "uos "
Void = "void "
Windows = "win "

[package]
format = '\[[pkg$version]($style)\]'

[perl]
format = '\[[perl ($version)]($style)\]'

[php]
format = '\[[php ($version)]($style)\]'

[pijul_channel]
format = '\[[pijul$channel]($style)\]'

[pixi]
format = '\[[pixi$version( $environment)]($style)\]'

[pulumi]
format = '\[[pulumi$stack]($style)\]'

[purescript]
format = '\[[purs ($version)]($style)\]'

[python]
format = '\[[py${pyenv_prefix}(${version})(\\($virtualenv\\))]($style)\]'

[quarto]
format = '\[[quarto ($version)]($style)\]'

[raku]
format = '\[[raku ($version-$vm_version)]($style)\]'

[red]
format = '\[[red ($version)]($style)\]'

[rlang]
symbol = "\\[r\\] "

[ruby]
symbol = "\\[rb\\] "

[rust]
symbol = "\\[rs\\] "

[scala]
format = '\[[scala ($version)]($style)\]'

[shell]
format = '\[[$indicator]($style)\]'

[spack]
format = '\[[spack$environment]($style)\]'

[solidity]
format = '\[[solidity ($version)]($style)\]'

[status]
format = '\[[status$status]($style)\]'

[sudo]
format = '\[[as sudo]($style)\]'

[swift]
format = '\[[swift ($version)]($style)\]'

[typst]
format = '\[[typst ($version)]($style)\]'

[vagrant]
format = '\[[vagrant ($version)]($style)\]'

[terraform]
format = '\[[terraform$workspace]($style)\]'

[xmake]
format = '\[[xmake ($version)]($style)\]'

[zig]
format = '\[[zig ($version)]($style)\]'
